### ISSUE TITLE
IMU send maxes out at ~135Hz

### ISSUE THREAD

**Issue by dpkoch** [BYU-MAGICC/ROSflight2#1]
A few things to try:
* Use the xx_send_buf() function instead of the xx_send() function; it's supposed to be more efficient
* Use the SCALED_IMU message type instead of HIGHRES_IMU; it's 22 bytes as opposed to 62
* If that still doesn't work, create a custom mavlink message (e.g. SMALL_IMU) that strips out the timestamp (4 bytes) and maybe the magnetometer(?) (6 bytes), leaving us with 18 or 12 bytes.

**Comment by dpkoch** [comment]
Got it working at up to 500Hz (when nothing else is going on) by switching to SMALL_IMU message type.

**Comment by superjax** [comment]
That's fantastic!!! Nice job!
