### ISSUE TITLE
Finish converting to float values

### ISSUE THREAD

**Issue by dpkoch** [BYU-MAGICC/ROSflight2#54]
There is currently some goofy stuff going on where we calculate values in floats, store them as ints, then convert them back to floats before we use them. There are also several parameters that should be converting to floats, such as the controller gains.

**Comment by dpkoch** [comment]
Partially addressed by #53.

**Comment by dpkoch** [comment]
Partially addressed by #55.

**Comment by superjax** [comment]
This is closed by #60
